### ISSUE TITLE
setup Jenkins

### ISSUE THREAD

**Issue by kugami** [bst-mug/n2c2#17]
https://jenkins.io/

- self-contained Java-based program, ready to run out-of-the-box, with packages for Windows, Mac OS X and other Unix-like operating systems
- extensible automation server, Jenkins can be used as a simple CI server or turned into the continuous delivery hub for any project

this needs to be done after the Google Cloud Service is up and running

**Comment by michelole** [comment]
Depends on #16 .

**Comment by michelole** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Plot+Plugin
