### ISSUE TITLE
Rule-based classifier

### ISSUE THREAD

**Issue by michelole** [bst-mug/n2c2#21]
To be eventually implemented by either @kasac or @steschu63, probably using regular expressions.

**Comment by michelole** [comment]
Depends on #20 (Zoning).

**Comment by michelole** [comment]
Top 2 worst classes so far are `DIETSUPP-2MOS` and `ABDOMINAL`. These would also be good places to start, as they're also not value-dependent.

**Comment by michelole** [comment]
Crazy idea: bootstrap rules out of the 10 annotated docs...

**Comment by kasac** [comment]
interesting idea. is it complicated? i could then try to improve them...

**Comment by michelole** [comment]
This is now finished.
