### ISSUE TITLE
Successful strategies from i2b2 shared tasks

### ISSUE THREAD

**Issue by michelole** [bst-mug/n2c2#5]
Take a look on what other people did in the past in similar tasks.

See https://dbmi.hms.harvard.edu/programs/healthcare-data-science-program/clinical-nlp-challenges/7-2014-deid-heartdisease

**Comment by kugami** [comment]
**According to this paper: "Identifying risk factors for heart disease over time: Overview of 2014 i2b2/UTHealth shared task Track 2"**

**general information** 
this task focused on identifying medical risk factors related to Coronary Artery Disease in the longitudinal medical records of diabetic patients 
a note about the corpus: the training data consisted of 60% of the total corpus (790 records) and the testing data consisted of the remaining 40% (514 records) 

**submissions -- what did other people do?** 
note: this will be listed based on the past ranking, so 1. equals first place in the past competition

**1st place:**
approach of mention level classification task, 
- using the spans highlighted by the annotators
- they reannotated two thirds of the training corpus
- standardized both the mention spans and annotated both positive and negative mentions 

this data was used for training, and then preprocessing: 
identification of section headers, negation words, modality words and output from ConText, 
rules were used for locating trigger words, medication and measurement, SVM classifiers were used to 
identify the validity and polarity of each mention, smoking status was identified by using a single 5-way classifier and a separate rule-based classifier for family history 

**2nd place:**
... to be continued ...

**Comment by michelole** [comment]
👍 
so... no neural nets?
